import API from '@/services';

const BASE_ENDPOINT = '/api/trello';

const members = {
  getMemberBoards: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/boards/${pathHash}`),
  getMember: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/${pathHash}`),
  updateMember: (id: string, data: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/members/${id}/${pathHash}`, data),
  getMemberField: (id: string, field: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/${field}/${pathHash}`),
  getMemberActions: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/actions/${pathHash}`),
  getMemberBoardBackgrounds: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/board-backgrounds/${pathHash}`),
  createMemberBoardBackground: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/board-backgrounds/${pathHash}`, payload),
  getMemberBoardBackground: (id: string, idBackground: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/board-backgrounds/${idBackground}/${pathHash}`),
  updateMemberBoardBackground: (id: string, idBackground: string, data: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/members/${id}/board-backgrounds/${idBackground}/${pathHash}`, data),
  deleteMemberBoardBackground: (id: string, idBackground: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/members/${id}/board-backgrounds/${idBackground}/${pathHash}`),
  getMemberBoardStars: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/boardStars/${pathHash}`),
  createMemberBoardStar: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/boardStars/${pathHash}`, payload),
  getMemberBoardStar: (id: string, idStar: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/boardStars/${idStar}/${pathHash}`),
  updateMemberBoardStar: (id: string, idStar: string, data: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/members/${id}/boardStars/${idStar}/${pathHash}`, data),
  deleteMemberBoardStar: (id: string, idStar: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/members/${id}/boardStars/${idStar}/${pathHash}`),
  getMemberBoardsInvited: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/boardsInvited/${pathHash}`),
  getMemberCards: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/cards/${pathHash}`),
  getMemberCustomBoardBackgrounds: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/customBoardBackgrounds/${pathHash}`),
  createMemberCustomBoardBackground: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/customBoardBackgrounds/${pathHash}`, payload),
  getMemberCustomBoardBackground: (id: string, idBackground: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/customBoardBackgrounds/${idBackground}/${pathHash}`),
  updateMemberCustomBoardBackground: (id: string, idBackground: string, data: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/members/${id}/customBoardBackgrounds/${idBackground}/${pathHash}`, data),
  deleteMemberCustomBoardBackground: (id: string, idBackground: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/members/${id}/customBoardBackgrounds/${idBackground}/${pathHash}`),
  getMemberCustomEmoji: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/customEmoji/${pathHash}`),
  createMemberCustomEmoji: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/customEmoji/${pathHash}`, payload),
  getMemberCustomStickers: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/customStickers/${pathHash}`),
  createMemberCustomSticker: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/customStickers/${pathHash}`, payload),
  getMemberNotifications: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/notifications/${pathHash}`),
  getMemberOrganizations: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/organizations/${pathHash}`),
  getMemberOrganizationsInvited: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/organizationsInvited/${pathHash}`),
  getMemberSavedSearches: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/savedSearches/${pathHash}`),
  createMemberSavedSearch: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/savedSearches/${pathHash}`, payload),
  getMemberSavedSearch: (id: string, idSearch: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/savedSearches/${idSearch}/${pathHash}`),
  updateMemberSavedSearch: (id: string, idSearch: string, data: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/members/${id}/savedSearches/${idSearch}/${pathHash}`, data),
  deleteMemberSavedSearch: (id: string, idSearch: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/members/${id}/savedSearches/${idSearch}/${pathHash}`),
  getMemberTokens: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/members/${id}/tokens/${pathHash}`),
  updateMemberAvatar: (id: string, data: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/avatar/${pathHash}`, data),
  dismissOneTimeMessages: (id: string, data: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/members/${id}/oneTimeMessagesDismissed/${pathHash}`, data),
};

const boards = {
  createBoard: (payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/boards/${pathHash}`, payload),
  getBoard: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/${pathHash}`),
  updateBoard: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/boards/${id}/${pathHash}`, payload),
  deleteBoard: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/boards/${id}/${pathHash}`),
  getCard: (id: string, idCard: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/cards/${idCard}/${pathHash}`),
  getCards: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/cards/${pathHash}`), // getBoardCards
  getFilteredCards: (id: string, filter: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/cards/${filter}/${pathHash}`),
  getLists: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/lists/${pathHash}`),
  createList: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/boards/${id}/lists/${pathHash}`, payload),
  getFilteredLists: (id: string, filter: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/lists/${filter}/${pathHash}`),
  getMembers: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/members/${pathHash}`),
  getLabels: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/boards/${id}/labels/${pathHash}`),
  updateMembers: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/boards/${id}/members/${pathHash}`, payload),
  updateMember: (id: string, idMember: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/boards/${id}/members/${idMember}/${pathHash}`, payload),
  removeMember: (id: string, idMember: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/boards/${id}/members/${idMember}/${pathHash}`),
  updateMembership: (id: string, idMembership: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/boards/${id}/memberships/${idMembership}/${pathHash}`, payload),
};

const lists = {
  getList: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/lists/${id}/${pathHash}`),
  createList: (payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/lists/${pathHash}`, payload),
  updateList: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/lists/${id}/${pathHash}`, payload),
  getCards: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/lists/${id}/cards/${pathHash}`),
  closeList: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/lists/${id}/closed/${pathHash}`, payload),
  archiveAllCards: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/lists/${id}/archive-all-cards/${pathHash}`, payload),
  moveAllCards: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/lists/${id}/move-all-cards/${pathHash}`, payload),
  changeBoard: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/lists/${id}/id-board/${pathHash}`, payload),
  updateField: (id: string, field: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/lists/${id}/${field}/${pathHash}`, payload),
  getActions: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/lists/${id}/actions/${pathHash}`),
  getBoard: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/lists/${id}/board/${pathHash}`),
};


const cards = {
  createCard: (payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${pathHash}`, payload),
  updateCard: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/${pathHash}`, payload),
  deleteCard: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/${pathHash}`),
  getCard: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/${pathHash}`),
  getField: (id: string, field: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/${field}/${pathHash}`),
  getActions: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/actions/${pathHash}`),
  getAttachments: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/attachments/${pathHash}`),
  createAttachment: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/attachments/${pathHash}`, payload),
  getAttachment: (id: string, idAttachment: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/attachments/${idAttachment}/${pathHash}`),
  deleteAttachment: (id: string, idAttachment: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/attachments/${idAttachment}/${pathHash}`),
  getBoard: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/board/${pathHash}`),
  getCheckItemStates: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/check-item-states/${pathHash}`),
  getChecklists: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/checklists/${pathHash}`),
  createChecklist: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/checklists/${pathHash}`, payload),
  getCheckItem: (id: string, idCheckItem: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/check-item/${idCheckItem}/${pathHash}`),
  updateCheckItem: (id: string, idCheckItem: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/check-item/${idCheckItem}/${pathHash}`, payload),
  deleteCheckItem: (id: string, idCheckItem: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/check-item/${idCheckItem}/${pathHash}`),
  getList: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/list/${pathHash}`),
  getMembers: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/members/${pathHash}`),
  getMembersVoted: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/members-voted/${pathHash}`),
  createMembersVoted: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/members-voted/${pathHash}`, payload),
  getPluginData: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/plugin-data/${pathHash}`),
  getStickers: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/stickers/${pathHash}`),
  createSticker: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/stickers/${pathHash}`, payload),
  getSticker: (id: string, idSticker: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/stickers/${idSticker}/${pathHash}`),
  updateSticker: (id: string, idSticker: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/stickers/${idSticker}/${pathHash}`, payload),
  deleteSticker: (id: string, idSticker: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/stickers/${idSticker}/${pathHash}`),
  updateActionsComment: (id: string, idAction: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/actions/${idAction}/comments/${pathHash}`, payload),
  deleteActionsComment: (id: string, idAction: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/actions/${idAction}/comments/${pathHash}`),
  updateCustomFieldItem: (id: string, idCustomField: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/custom-field/${idCustomField}/item/${pathHash}`, payload),
  updateCustomFields: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/custom-fields/${pathHash}`, payload),
  getCustomFieldItems: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/cards/${id}/custom-field-items/${pathHash}`),
  createActionsComment: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/actions/comments/${pathHash}`, payload),
  createIdLabels: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/id-labels/${pathHash}`, payload),
  addMember: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/id-members/${pathHash}`, payload),
  createLabels: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/labels/${pathHash}`, payload),
  markAssociatedNotificationsRead: (id: string, pathHash: string) => API.post(`${BASE_ENDPOINT}/cards/${id}/mark-associated-notifications-read/${pathHash}`),
  deleteIdLabels: (id: string, idLabel: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/id-labels/${idLabel}/${pathHash}`),
  deleteMember: (id: string, idMember: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/id-members/${idMember}/${pathHash}`),
  deleteMembersVoted: (id: string, idMember: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/members-voted/${idMember}/${pathHash}`),
  updateChecklistCheckItem: (id: string, idChecklist: string, idCheckItem: string, pathHash: string) => API.put(`${BASE_ENDPOINT}/cards/${id}/checklist/${idChecklist}/checkItem/${idCheckItem}/${pathHash}`),
  deleteChecklist: (id: string, idChecklist: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/cards/${id}/checklists/${idChecklist}/${pathHash}`),
};

const organizations = {
  createOrganization: (payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/organizations/${pathHash}`, payload),
  getOrganization: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/${pathHash}`),
  updateOrganization: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/organizations/${id}/${pathHash}`, payload),
  deleteOrganization: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/${pathHash}`),
  getField: (id: string, field: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/${field}/${pathHash}`),
  getActions: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/actions/${pathHash}`),
  getBoards: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/boards/${pathHash}`),
  getExports: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/exports/${pathHash}`),
  createExport: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/organizations/${id}/exports/${pathHash}`, payload),
  getMembers: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/members/${pathHash}`),
  updateMembers: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/organizations/${id}/members/${pathHash}`, payload),
  getMemberships: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/memberships/${pathHash}`),
  getMembership: (id: string, idMembership: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/memberships/${idMembership}/${pathHash}`),
  getPluginData: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/plugin-data/${pathHash}`),
  getTags: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/tags/${pathHash}`),
  createTag: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/organizations/${id}/tags/${pathHash}`, payload),
  updateMember: (id: string, idMember: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/organizations/${id}/members/${idMember}/${pathHash}`, payload),
  deactivateMember: (id: string, idMember: string, pathHash: string) => API.put(`${BASE_ENDPOINT}/organizations/${id}/members/${idMember}/${pathHash}/deactivated`),
  uploadLogo: (id: string, payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/organizations/${id}/logo/${pathHash}`, payload),
  deleteLogo: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/logo/${pathHash}`),
  removeAllMembers: (id: string, idMember: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/members/${idMember}/${pathHash}/all`),
  deleteAssociatedDomain: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/prefs/associated-domain/${pathHash}`),
  deleteOrgInviteRestrict: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/prefs/org-invite-restrict/${pathHash}`),
  deleteTag: (id: string, idTag: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/organizations/${id}/tags/${idTag}/${pathHash}`),
  getNewBillableGuests: (id: string, idBoard: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/organizations/${id}/new-billable-guests/${idBoard}/${pathHash}`),
};

const labels = {
  getLabel: (id: string, pathHash: string) => API.get(`${BASE_ENDPOINT}/labels/${id}/${pathHash}`),
  updateLabel: (id: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/labels/${id}/${pathHash}`, payload),
  deleteLabel: (id: string, pathHash: string) => API.delete(`${BASE_ENDPOINT}/labels/${id}/${pathHash}`),
  updateField: (id: string, field: string, payload: any, pathHash: string) => API.put(`${BASE_ENDPOINT}/labels/${id}/${field}/${pathHash}`, payload),
  createLabel: (payload: any, pathHash: string) => API.post(`${BASE_ENDPOINT}/labels/${pathHash}`, payload),
};

const trello = {
  getResource: (user_id: any, path_id: any) => API.get(`${BASE_ENDPOINT}/${user_id}/${path_id}`),
  setAuthToken: (payload = {}) => API.post(`${BASE_ENDPOINT}/access-token`, payload),
  setTokenMember: (payload = {}) => API.post(`${BASE_ENDPOINT}/token-member`, payload),
}


export default {
  members,
  boards,
  lists,
  cards,
  organizations,
  labels,
  trello,
};
